Question 1:

In [1]:
import numpy as np
a=np.array([2,4,6,8,9])

# a.
for i in range(0,5):
  a[i]=a[i]+2
print(a)

# b.
for i in range(0,5):
  a[i]=a[i]*3
print(a)

# c.
for i in range(0,5):
  a[i]=a[i]/2
print(a)

[ 4  6  8 10 11]
[12 18 24 30 33]
[ 6  9 12 15 16]


Question 2a:

In [2]:
import numpy as np
a=np.array([1,2,3,6,4,5])
a=a[::-1]
print(a)

[5 4 6 3 2 1]


Question 2b:

In [3]:
import numpy as np

occurence=[]

# i.
x=np.array([1,2,3,4,5,1,2,1,1,1])
for i in range(1,6):
  count_occ=np.count_nonzero(x==i)
  occurence.append(count_occ)

max_occ=max(occurence)
max_index=occurence.index(max_occ)

print(f"{max_index+1} occures most frequently and {max_occ} times")

# ii.
y=np.array([1,1,1,2,3,4,2,4,3,3]) #can use same upper code



1 occures most frequently and 5 times


Question 3:

In [4]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[2][0])

20
70


Question 4:

In [6]:
import numpy as np
shubham=np.linspace(10,100,25)
print(shubham)
print(shubham.ndim)
print(shubham.shape)
print(shubham.size)

print(shubham.dtype)
print(shubham.nbytes)
print(shubham.reshape(5,5))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]


Question 5:

In [7]:
import numpy as np
ucs420_shubham=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_shubham.mean())

col_median = np.median(ucs420_shubham, axis=0)
row_median = np.median(ucs420_shubham, axis=1)
print("Column-wise median:", col_median)
print("Row-wise median:", row_median)

print(np.max(ucs420_shubham))
print(np.min(ucs420_shubham))

reshaped_ucs420_shubham=ucs420_shubham.reshape(4,3)
print(reshaped_ucs420_shubham.reshape(4,3))

resize_ucs420_shubham=np.resize(reshaped_ucs420_shubham,(2,3))
print(resize_ucs420_shubham)


43.333333333333336
Column-wise median: [50. 20. 30. 40.]
Row-wise median: [25.  65.  27.5]
90
10
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
